use_frameworks!

target 'UICollectionUpdates_Example' do
  pod 'UICollectionUpdates', :path => '../'

  target 'UICollectionUpdates_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase' , '~> 2.1.4'
  end
end
